### ISSUE TITLE
Compatibility With Farmers Delight: Refabricated

### ISSUE THREAD

**Issue by PolyframeX** [ChefMooon/frights-delight#2]
Currently, the mod does not have compatibility with Farmer's Delight Refabricated, and immediately crashes when being used with. It would be very nice if it would be possible to add compatibility.

**Comment by ChefMooon** [comment]
I appreciate you opening an issue this should be fixed with the next update of Fright's Delight(V1.0.2). Just ensure you are using Farmer's Delight Refabricated V2.0.10 and above. I will close this issue once the release is out.

**Comment by ChefMooon** [comment]
Update has been released [Curseforge](https://legacy.curseforge.com/minecraft/mc-mods/frights-delight/files/5230503), [Modrinth](https://modrinth.com/mod/frights-delight/version/fabric-1.20.1-1.0.2). Please let me know if you have any issues.
